$(document).ready(function(){
    $("#design-image").click(function(){
      $("#design-image").toggle()
      $("#design").toggle();
    });
    $("#design").click(function(){
      $("#design").toggle()
      $("#design-image").toggle()
    });


    $("#development-image").click(function(){
        $("#development-image").toggle();
        $("#development").toggle();
    });
    $("#development").click(function(){
        $("#development").toggle();
        $("#development-image").toggle();    
});

    $("#product-image").click(function(){
        $("#product-image").toggle();
        $("#product").toggle();
    });
    $("#product").click(function(){
        $("#product").toggle();
        $("#product-image").toggle();    
});
});
$(document).ready(function(){
  $("#work1").mouseover(function(){
    $(".overlay1").show();
  }).mouseout(function(){
    $(".overlay1").hide();
  });
});
$(document).ready(function(){
  $("#work2").mouseover(function(){
    $(".overlay2").show();
  }).mouseout(function(){
    $(".overlay2").hide();
  });
});
$(document).ready(function(){
  $("#work3").mouseover(function(){
    $(".overlay3").show();
  }).mouseout(function(){
    $(".overlay3").hide();
  });
});
$(document).ready(function(){
  $("#work4").mouseover(function(){
    $(".overlay4").show();
  }).mouseout(function(){
    $(".overlay4").hide();
  });
});
$(document).ready(function(){
  $("#work5").mouseover(function(){
    $(".overlay5").show();
  }).mouseout(function(){
    $(".overlay5").hide();
  });
});
$(document).ready(function(){
  $("#work6").mouseover(function(){
    $(".overlay6").show();
  }).mouseout(function(){
    $(".overlay6").hide();
  });
});
$(document).ready(function(){
  $("#work7").mouseover(function(){
    $(".overlay7").show();
  }).mouseout(function(){
    $(".overlay7").hide();
  });
});
$(document).ready(function(){
  $("#work8").mouseover(function(){
    $(".overlay8").show();
  }).mouseout(function(){
    $(".overlay8").hide();
  });
});